---
rvm:
- 1.9.3
bundler_args: --without development
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script: rake test\[standard]
notifications:
  webhooks: http://emberjs-master-builds.herokuapp.com/upload/ember.js
  campfire:
  - secure: |-
      ia5CUz3FeqK+s238B9ApRz1vt/qpM/WtI5HlYS7GH5WPBbC5vsSUIwV9IqM8
      HKvTwLQKHUP5e+6I7E40/ofbQycsNSeglJ0mRRzdLe2SeN68uPsjuy5AKnpn
      KpIzGa9OC5tZfN/RqJskLuP8QRvqNCLPyesY1E5GM7lTKYa92PM=
branches:
  except:
  - latest-builds
  - release-builds
